name: mirror_todo
description: This is a Todo app that shows mirrored text. 

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  drift: ^2.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.0
  riverpod_annotation: ^1.0.6
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  pedantic_mono: ^1.20.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true

  fonts:
    - family: MPLUS1
      fonts:
        - asset: assets/fonts/Mplus1-Regular.ttf